### ISSUE TITLE
请问ETGNN编码不同用户序列之间的协作信号是只限于一个batch内的用户吗

### ISSUE THREAD

**Issue by liyifo** [yule-BUAA/ETGNN#1]

**Comment by yule-BUAA** [comment]
你好，

ETGNN学习的协同信号并不限定于batch，而是通过整个时序图上的高阶信息聚合学习协同信号。具体来说，ETGNN首先为所有的用户和集合的序列构建时序图，然后对于每个用户进行逐层的邻居消息聚合，只要邻居节点能够通过特定的跳数连接到目标用户，其信息就会被目标节点聚合。

**Comment by liyifo** [comment]
> 你好，
> 
> ETGNN学习的协同信号并不限定于batch，而是通过整个时序图上的高阶信息聚合学习协同信号。具体来说，ETGNN首先为所有的用户和集合的序列构建时序图，然后对于每个用户进行逐层的邻居消息聚合，只要邻居节点能够通过特定的跳数连接到目标用户，其信息就会被目标节点聚合。

谢谢您的回复，我理解了，感谢您所作的贡献。
